# -*- coding: utf-8 -*-
"""
@author: Connor J Newstead
"""

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    
    """
        Class for the GUI.
        
        This contains all layouts, widgets, styles etc
        """
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1141, 579)
        MainWindow.setStyleSheet("*{\n"
"border:none;\n"
"background-color: transparent;\n"
"background: transparent;\n"
"padding: 0;\n"
"margin: 0;\n"
"color: #fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color: #1f232a;\n"
"}\n"
"#LeftMenuSubContainer{\n"
"    background-color: #16191d;\n"
"}\n"
"#LeftMenuSubContainer QPushButton{\n"
"    text-align: left;\n"
"    padding: 5px 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"#CenterMenuSubContainer QPushButton{\n"
"    text-align: left;\n"
"    background-color: #16191d;\n"
"    padding: 5px 5px;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"#RightMainContainer{\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"#frame_4{\n"
"background-color: #16191d;\n"
"border-radius: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LeftMenuContainer = QtWidgets.QWidget(self.centralwidget)
        self.LeftMenuContainer.setMouseTracking(False)
        self.LeftMenuContainer.setObjectName("LeftMenuContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.LeftMenuContainer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LeftMenuSubContainer = QtWidgets.QWidget(self.LeftMenuContainer)
        self.LeftMenuSubContainer.setObjectName("LeftMenuSubContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.LeftMenuSubContainer)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.LeftMenuSubContainer)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MenuButton = QtWidgets.QPushButton(self.frame)
        self.MenuButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons white/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MenuButton.setIcon(icon)
        self.MenuButton.setIconSize(QtCore.QSize(24, 24))
        self.MenuButton.setObjectName("MenuButton")
        self.verticalLayout_2.addWidget(self.MenuButton, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.LeftMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.OpenButton = QtWidgets.QPushButton(self.frame_2)
        self.OpenButton.setStyleSheet("background-color: #1f232a;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons white/navigation.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenButton.setIcon(icon1)
        self.OpenButton.setIconSize(QtCore.QSize(24, 24))
        self.OpenButton.setObjectName("OpenButton")
        self.verticalLayout_3.addWidget(self.OpenButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.DCIButton = QtWidgets.QPushButton(self.frame_2)
        self.DCIButton.setStyleSheet("background-color: #1f232a;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icons white/codepen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DCIButton.setIcon(icon2)
        self.DCIButton.setIconSize(QtCore.QSize(24, 24))
        self.DCIButton.setObjectName("DCIButton")
        self.verticalLayout_3.addWidget(self.DCIButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.drbutton = QtWidgets.QPushButton(self.frame_2)
        self.drbutton.setStyleSheet("background-color: #1f232a;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icons white/codesandbox.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.drbutton.setIcon(icon3)
        self.drbutton.setIconSize(QtCore.QSize(24, 24))
        self.drbutton.setObjectName("drbutton")
        self.verticalLayout_3.addWidget(self.drbutton)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.frame_3 = QtWidgets.QFrame(self.LeftMenuSubContainer)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.HelpButton = QtWidgets.QPushButton(self.frame_3)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icons white/help-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HelpButton.setIcon(icon4)
        self.HelpButton.setIconSize(QtCore.QSize(24, 24))
        self.HelpButton.setObjectName("HelpButton")
        self.verticalLayout_4.addWidget(self.HelpButton)
        self.verticalLayout.addWidget(self.frame_3, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_2.addWidget(self.LeftMenuSubContainer, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.LeftMenuContainer, 0, QtCore.Qt.AlignLeft)
        self.CenterMenuContainer = QtWidgets.QWidget(self.centralwidget)
        self.CenterMenuContainer.setMaximumSize(QtCore.QSize(250, 16777215))
        self.CenterMenuContainer.setObjectName("CenterMenuContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.CenterMenuContainer)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.CenterMenuSubContainer = QtWidgets.QWidget(self.CenterMenuContainer)
        self.CenterMenuSubContainer.setMinimumSize(QtCore.QSize(150, 0))
        self.CenterMenuSubContainer.setObjectName("CenterMenuSubContainer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.CenterMenuSubContainer)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.CenterMenuSubContainer)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.DataOptions = QtWidgets.QLabel(self.frame_4)
        self.DataOptions.setAlignment(QtCore.Qt.AlignCenter)
        self.DataOptions.setObjectName("DataOptions")
        self.horizontalLayout_3.addWidget(self.DataOptions)
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Icons white/trending-up.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon5)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.ToolsMenu = QtWidgets.QStackedWidget(self.CenterMenuSubContainer)
        self.ToolsMenu.setObjectName("ToolsMenu")
        self.openpage = QtWidgets.QWidget()
        self.openpage.setObjectName("openpage")
        self.frame_6 = QtWidgets.QFrame(self.openpage)
        self.frame_6.setGeometry(QtCore.QRect(9, 65, 211, 421))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.openmaskedit = QtWidgets.QTextEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openmaskedit.sizePolicy().hasHeightForWidth())
        self.openmaskedit.setSizePolicy(sizePolicy)
        self.openmaskedit.setMaximumSize(QtCore.QSize(16777215, 15))
        self.openmaskedit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.openmaskedit.setObjectName("openmaskedit")
        self.gridLayout_2.addWidget(self.openmaskedit, 5, 1, 1, 1)
        self.openmzscsv = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openmzscsv.sizePolicy().hasHeightForWidth())
        self.openmzscsv.setSizePolicy(sizePolicy)
        self.openmzscsv.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Icons white/file-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openmzscsv.setIcon(icon6)
        self.openmzscsv.setIconSize(QtCore.QSize(24, 24))
        self.openmzscsv.setObjectName("openmzscsv")
        self.gridLayout_2.addWidget(self.openmzscsv, 3, 2, 1, 1)
        self.opendataedit = QtWidgets.QTextEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opendataedit.sizePolicy().hasHeightForWidth())
        self.opendataedit.setSizePolicy(sizePolicy)
        self.opendataedit.setMaximumSize(QtCore.QSize(16777215, 15))
        self.opendataedit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.opendataedit.setObjectName("opendataedit")
        self.gridLayout_2.addWidget(self.opendataedit, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 4, 1, 1)
        self.openmaskbutton = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openmaskbutton.sizePolicy().hasHeightForWidth())
        self.openmaskbutton.setSizePolicy(sizePolicy)
        self.openmaskbutton.setText("")
        self.openmaskbutton.setIcon(icon6)
        self.openmaskbutton.setIconSize(QtCore.QSize(24, 24))
        self.openmaskbutton.setObjectName("openmaskbutton")
        self.gridLayout_2.addWidget(self.openmaskbutton, 5, 2, 1, 1)
        self.opendatacsvbutton = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opendatacsvbutton.sizePolicy().hasHeightForWidth())
        self.opendatacsvbutton.setSizePolicy(sizePolicy)
        self.opendatacsvbutton.setText("")
        self.opendatacsvbutton.setIcon(icon6)
        self.opendatacsvbutton.setIconSize(QtCore.QSize(24, 24))
        self.opendatacsvbutton.setObjectName("opendatacsvbutton")
        self.gridLayout_2.addWidget(self.opendatacsvbutton, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 12, 2, 1, 1)
        self.embeddingnpyedit = QtWidgets.QTextEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.embeddingnpyedit.sizePolicy().hasHeightForWidth())
        self.embeddingnpyedit.setSizePolicy(sizePolicy)
        self.embeddingnpyedit.setMaximumSize(QtCore.QSize(16777215, 15))
        self.embeddingnpyedit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.embeddingnpyedit.setObjectName("embeddingnpyedit")
        self.gridLayout_2.addWidget(self.embeddingnpyedit, 7, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 1)
        self.openmzsedit = QtWidgets.QTextEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openmzsedit.sizePolicy().hasHeightForWidth())
        self.openmzsedit.setSizePolicy(sizePolicy)
        self.openmzsedit.setMaximumSize(QtCore.QSize(16777215, 15))
        self.openmzsedit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.openmzsedit.setObjectName("openmzsedit")
        self.gridLayout_2.addWidget(self.openmzsedit, 3, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 1)
        self.openmatedit = QtWidgets.QTextEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openmatedit.sizePolicy().hasHeightForWidth())
        self.openmatedit.setSizePolicy(sizePolicy)
        self.openmatedit.setMaximumSize(QtCore.QSize(16777215, 15))
        self.openmatedit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.openmatedit.setObjectName("openmatedit")
        self.gridLayout_2.addWidget(self.openmatedit, 1, 1, 1, 1)
        self.openembeddingnpy = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openembeddingnpy.sizePolicy().hasHeightForWidth())
        self.openembeddingnpy.setSizePolicy(sizePolicy)
        self.openembeddingnpy.setText("")
        self.openembeddingnpy.setIcon(icon6)
        self.openembeddingnpy.setIconSize(QtCore.QSize(24, 24))
        self.openembeddingnpy.setObjectName("openembeddingnpy")
        self.gridLayout_2.addWidget(self.openembeddingnpy, 7, 2, 1, 1)
        self.openmatbutton = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openmatbutton.sizePolicy().hasHeightForWidth())
        self.openmatbutton.setSizePolicy(sizePolicy)
        self.openmatbutton.setText("")
        self.openmatbutton.setIcon(icon6)
        self.openmatbutton.setIconSize(QtCore.QSize(24, 24))
        self.openmatbutton.setObjectName("openmatbutton")
        self.gridLayout_2.addWidget(self.openmatbutton, 1, 2, 1, 1)
        self.ToolsMenu.addWidget(self.openpage)
        self.dcipage = QtWidgets.QWidget()
        self.dcipage.setObjectName("dcipage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.dcipage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.drlabel = QtWidgets.QLabel(self.dcipage)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.drlabel.setFont(font)
        self.drlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.drlabel.setObjectName("drlabel")
        self.verticalLayout_7.addWidget(self.drlabel, 0, QtCore.Qt.AlignTop)
        self.frame_5 = QtWidgets.QFrame(self.dcipage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame_5.setFont(font)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setObjectName("gridLayout")
        self.samplesrandommethod_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.samplesrandommethod_2.setFont(font)
        self.samplesrandommethod_2.setObjectName("samplesrandommethod_2")
        self.gridLayout.addWidget(self.samplesrandommethod_2, 7, 0, 1, 2)
        self.randomsamples = QtWidgets.QSpinBox(self.frame_5)
        self.randomsamples.setMaximum(999999)
        self.randomsamples.setProperty("value", 2000)
        self.randomsamples.setObjectName("randomsamples")
        self.gridLayout.addWidget(self.randomsamples, 5, 1, 1, 1)
        self.sampleslabel = QtWidgets.QLabel(self.frame_5)
        self.sampleslabel.setObjectName("sampleslabel")
        self.gridLayout.addWidget(self.sampleslabel, 2, 0, 1, 1)
        self.samplesrandommethod_3 = QtWidgets.QLabel(self.frame_5)
        self.samplesrandommethod_3.setObjectName("samplesrandommethod_3")
        self.gridLayout.addWidget(self.samplesrandommethod_3, 10, 0, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.frame_5)
        self.horizontalSlider_2.setMaximum(999999)
        self.horizontalSlider_2.setPageStep(10)
        self.horizontalSlider_2.setProperty("value", 10)
        self.horizontalSlider_2.setTracking(True)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout.addWidget(self.horizontalSlider_2, 5, 0, 1, 1)
        self.maxexaggerationinput_2 = QtWidgets.QSpinBox(self.frame_5)
        self.maxexaggerationinput_2.setMinimum(10)
        self.maxexaggerationinput_2.setMaximum(99999)
        self.maxexaggerationinput_2.setProperty("value", 50)
        self.maxexaggerationinput_2.setObjectName("maxexaggerationinput_2")
        self.gridLayout.addWidget(self.maxexaggerationinput_2, 12, 1, 1, 1)
        self.runoptbutton = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runoptbutton.sizePolicy().hasHeightForWidth())
        self.runoptbutton.setSizePolicy(sizePolicy)
        self.runoptbutton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Icons white/arrow-right-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runoptbutton.setIcon(icon7)
        self.runoptbutton.setIconSize(QtCore.QSize(24, 24))
        self.runoptbutton.setObjectName("runoptbutton")
        self.gridLayout.addWidget(self.runoptbutton, 13, 1, 1, 1)
        self.rundcilabel_2 = QtWidgets.QLabel(self.frame_5)
        self.rundcilabel_2.setObjectName("rundcilabel_2")
        self.gridLayout.addWidget(self.rundcilabel_2, 13, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_5)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 8, 1, 1, 1)
        self.samplesrandommethod_4 = QtWidgets.QLabel(self.frame_5)
        self.samplesrandommethod_4.setObjectName("samplesrandommethod_4")
        self.gridLayout.addWidget(self.samplesrandommethod_4, 11, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 0, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 4, 1, 1, 1)
        self.drmethodlabel = QtWidgets.QLabel(self.frame_5)
        self.drmethodlabel.setObjectName("drmethodlabel")
        self.gridLayout.addWidget(self.drmethodlabel, 8, 0, 1, 1)
        self.samplesrandommethod_6 = QtWidgets.QLabel(self.frame_5)
        self.samplesrandommethod_6.setObjectName("samplesrandommethod_6")
        self.gridLayout.addWidget(self.samplesrandommethod_6, 12, 0, 1, 1)
        self.samplesrandommethod = QtWidgets.QLabel(self.frame_5)
        self.samplesrandommethod.setObjectName("samplesrandommethod")
        self.gridLayout.addWidget(self.samplesrandommethod, 4, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.frame_5)
        self.checkBox.setText("")
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 1, 1, 1)
        self.rundcibutton = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rundcibutton.sizePolicy().hasHeightForWidth())
        self.rundcibutton.setSizePolicy(sizePolicy)
        self.rundcibutton.setText("")
        self.rundcibutton.setIcon(icon7)
        self.rundcibutton.setIconSize(QtCore.QSize(24, 24))
        self.rundcibutton.setObjectName("rundcibutton")
        self.gridLayout.addWidget(self.rundcibutton, 6, 1, 1, 1)
        self.rundcilabel = QtWidgets.QLabel(self.frame_5)
        self.rundcilabel.setObjectName("rundcilabel")
        self.gridLayout.addWidget(self.rundcilabel, 6, 0, 1, 1)
        self.initlabel = QtWidgets.QLabel(self.frame_5)
        self.initlabel.setObjectName("initlabel")
        self.gridLayout.addWidget(self.initlabel, 9, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 14, 0, 1, 1)
        self.clustersamplespercent = QtWidgets.QSpinBox(self.frame_5)
        self.clustersamplespercent.setMaximum(100)
        self.clustersamplespercent.setProperty("value", 5)
        self.clustersamplespercent.setObjectName("clustersamplespercent")
        self.gridLayout.addWidget(self.clustersamplespercent, 3, 1, 1, 1)
        self.maxneighboursinput = QtWidgets.QSpinBox(self.frame_5)
        self.maxneighboursinput.setMaximum(99999)
        self.maxneighboursinput.setProperty("value", 3000)
        self.maxneighboursinput.setObjectName("maxneighboursinput")
        self.gridLayout.addWidget(self.maxneighboursinput, 10, 1, 1, 1)
        self.loadspectraldatabutton = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadspectraldatabutton.sizePolicy().hasHeightForWidth())
        self.loadspectraldatabutton.setSizePolicy(sizePolicy)
        self.loadspectraldatabutton.setText("")
        self.loadspectraldatabutton.setIcon(icon6)
        self.loadspectraldatabutton.setIconSize(QtCore.QSize(24, 24))
        self.loadspectraldatabutton.setObjectName("loadspectraldatabutton")
        self.gridLayout.addWidget(self.loadspectraldatabutton, 1, 1, 1, 1)
        self.loadmebeddingcsvedit = QtWidgets.QTextEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadmebeddingcsvedit.sizePolicy().hasHeightForWidth())
        self.loadmebeddingcsvedit.setSizePolicy(sizePolicy)
        self.loadmebeddingcsvedit.setMaximumSize(QtCore.QSize(16777215, 15))
        self.loadmebeddingcsvedit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.loadmebeddingcsvedit.setObjectName("loadmebeddingcsvedit")
        self.gridLayout.addWidget(self.loadmebeddingcsvedit, 1, 0, 1, 1)
        self.maxexaggerationinput = QtWidgets.QSpinBox(self.frame_5)
        self.maxexaggerationinput.setMaximum(99999)
        self.maxexaggerationinput.setProperty("value", 1000)
        self.maxexaggerationinput.setObjectName("maxexaggerationinput")
        self.gridLayout.addWidget(self.maxexaggerationinput, 11, 1, 1, 1)
        self.clustersamplesslider = QtWidgets.QSlider(self.frame_5)
        self.clustersamplesslider.setMaximum(100)
        self.clustersamplesslider.setProperty("value", 5)
        self.clustersamplesslider.setSliderPosition(5)
        self.clustersamplesslider.setOrientation(QtCore.Qt.Horizontal)
        self.clustersamplesslider.setObjectName("clustersamplesslider")
        self.gridLayout.addWidget(self.clustersamplesslider, 3, 0, 1, 1)
        self.initselectionbox = QtWidgets.QComboBox(self.frame_5)
        self.initselectionbox.setObjectName("initselectionbox")
        self.initselectionbox.addItem("")
        self.initselectionbox.addItem("")
        self.initselectionbox.addItem("")
        self.gridLayout.addWidget(self.initselectionbox, 9, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_5)
        self.statuslabel = QtWidgets.QLabel(self.dcipage)
        self.statuslabel.setObjectName("statuslabel")
        self.verticalLayout_7.addWidget(self.statuslabel)
        self.ToolsMenu.addWidget(self.dcipage)
        self.drselectionpage = QtWidgets.QWidget()
        self.drselectionpage.setObjectName("drselectionpage")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.drselectionpage)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.DataAnalysisLabel = QtWidgets.QLabel(self.drselectionpage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DataAnalysisLabel.setFont(font)
        self.DataAnalysisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DataAnalysisLabel.setObjectName("DataAnalysisLabel")
        self.verticalLayout_8.addWidget(self.DataAnalysisLabel, 0, QtCore.Qt.AlignTop)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem9)
        self.dr_tsne = QtWidgets.QPushButton(self.drselectionpage)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/Icons white/sunset.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dr_tsne.setIcon(icon8)
        self.dr_tsne.setIconSize(QtCore.QSize(24, 24))
        self.dr_tsne.setObjectName("dr_tsne")
        self.verticalLayout_8.addWidget(self.dr_tsne)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem10)
        self.ToolsMenu.addWidget(self.drselectionpage)
        self.tsnepage = QtWidgets.QWidget()
        self.tsnepage.setObjectName("tsnepage")
        self.frame_7 = QtWidgets.QFrame(self.tsnepage)
        self.frame_7.setGeometry(QtCore.QRect(10, 90, 210, 420))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 5, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_7)
        self.spinBox_2.setMaximum(99999)
        self.spinBox_2.setProperty("value", 4)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_3.addWidget(self.spinBox_2, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 4, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_3, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.tsnecreateembbutton = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsnecreateembbutton.sizePolicy().hasHeightForWidth())
        self.tsnecreateembbutton.setSizePolicy(sizePolicy)
        self.tsnecreateembbutton.setText("")
        self.tsnecreateembbutton.setIcon(icon7)
        self.tsnecreateembbutton.setIconSize(QtCore.QSize(24, 24))
        self.tsnecreateembbutton.setObjectName("tsnecreateembbutton")
        self.gridLayout_3.addWidget(self.tsnecreateembbutton, 7, 2, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame_7)
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setMaximum(3)
        self.spinBox_3.setProperty("value", 3)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_3.addWidget(self.spinBox_3, 5, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.frame_7)
        self.spinBox.setMaximum(99999)
        self.spinBox.setProperty("value", 12)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_3.addWidget(self.spinBox, 1, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_2, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 6, 0, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.ToolsMenu.addWidget(self.tsnepage)
        self.helppage = QtWidgets.QWidget()
        self.helppage.setObjectName("helppage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.helppage)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.helppage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.frame_8 = QtWidgets.QFrame(self.helppage)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.whatdata_helpbtn = QtWidgets.QPushButton(self.frame_8)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/Icons white/alert-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.whatdata_helpbtn.setIcon(icon9)
        self.whatdata_helpbtn.setObjectName("whatdata_helpbtn")
        self.verticalLayout_11.addWidget(self.whatdata_helpbtn)
        self.matbroken_helpbtn = QtWidgets.QPushButton(self.frame_8)
        self.matbroken_helpbtn.setIcon(icon9)
        self.matbroken_helpbtn.setObjectName("matbroken_helpbtn")
        self.verticalLayout_11.addWidget(self.matbroken_helpbtn)
        self.csvbroken_helpbtn = QtWidgets.QPushButton(self.frame_8)
        self.csvbroken_helpbtn.setIcon(icon9)
        self.csvbroken_helpbtn.setObjectName("csvbroken_helpbtn")
        self.verticalLayout_11.addWidget(self.csvbroken_helpbtn)
        self.HowDCI_helpbtn = QtWidgets.QPushButton(self.frame_8)
        self.HowDCI_helpbtn.setIcon(icon9)
        self.HowDCI_helpbtn.setObjectName("HowDCI_helpbtn")
        self.verticalLayout_11.addWidget(self.HowDCI_helpbtn)
        self.HowBayes_helpbtn = QtWidgets.QPushButton(self.frame_8)
        self.HowBayes_helpbtn.setIcon(icon9)
        self.HowBayes_helpbtn.setObjectName("HowBayes_helpbtn")
        self.verticalLayout_11.addWidget(self.HowBayes_helpbtn)
        self.Whatparams_helpbtn = QtWidgets.QPushButton(self.frame_8)
        self.Whatparams_helpbtn.setIcon(icon9)
        self.Whatparams_helpbtn.setObjectName("Whatparams_helpbtn")
        self.verticalLayout_11.addWidget(self.Whatparams_helpbtn)
        self.Whatoutputs_helpbtn = QtWidgets.QPushButton(self.frame_8)
        self.Whatoutputs_helpbtn.setIcon(icon9)
        self.Whatoutputs_helpbtn.setObjectName("Whatoutputs_helpbtn")
        self.verticalLayout_11.addWidget(self.Whatoutputs_helpbtn)
        self.loadingbeecheck = QtWidgets.QCheckBox(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadingbeecheck.sizePolicy().hasHeightForWidth())
        self.loadingbeecheck.setSizePolicy(sizePolicy)
        self.loadingbeecheck.setObjectName("loadingbeecheck")
        self.verticalLayout_11.addWidget(self.loadingbeecheck)
        self.verticalLayout_9.addWidget(self.frame_8)
        self.ToolsMenu.addWidget(self.helppage)
        self.verticalLayout_6.addWidget(self.ToolsMenu)
        self.verticalLayout_5.addWidget(self.CenterMenuSubContainer, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.CenterMenuContainer)
        self.RightMainContainer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RightMainContainer.sizePolicy().hasHeightForWidth())
        self.RightMainContainer.setSizePolicy(sizePolicy)
        self.RightMainContainer.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.RightMainContainer.setObjectName("RightMainContainer")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.RightMainContainer)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.stackedWidget = QtWidgets.QStackedWidget(self.RightMainContainer)
        self.stackedWidget.setObjectName("stackedWidget")
        self.figure_page_layout = QtWidgets.QVBoxLayout()
        self.figure_page = QtWidgets.QWidget()
        self.figure_page.setObjectName("figure_page")
        self.figure_page.setLayout(self.figure_page_layout)
        self.stackedWidget.addWidget(self.figure_page)
        self.loading_screen_layout = QtWidgets.QVBoxLayout()
        self.loading_screen = QtWidgets.QWidget()
        self.loading_screen.setObjectName("loading_screen")
        self.loading_screen.setLayout(self.loading_screen_layout)
        self.stackedWidget.addWidget(self.loading_screen)
        self.verticalLayout_10.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.RightMainContainer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.ToolsMenu.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dimensional Cophenetic Integrity"))
        self.OpenButton.setText(_translate("MainWindow", "  Open"))
        self.DCIButton.setText(_translate("MainWindow", "DCI"))
        self.drbutton.setText(_translate("MainWindow", "Dimensionality Reduction"))
        self.HelpButton.setText(_translate("MainWindow", "  Help"))
        self.DataOptions.setText(_translate("MainWindow", "Tools"))
        self.openmaskedit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Open mask npy/csv</p></body></html>"))
        self.opendataedit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Open data npy/csv</p></body></html>"))
        self.embeddingnpyedit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Open Embedding dict</p></body></html>"))
        self.openmzsedit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Open mzs npy/csv</p></body></html>"))
        self.openmatedit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Open .mat</p></body></html>"))
        self.drlabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Dimensional Cophenetic</p><p align=\"center\">Integrity</p></body></html>"))
        self.samplesrandommethod_2.setText(_translate("MainWindow", "Bayesian Optimisation"))
        self.sampleslabel.setText(_translate("MainWindow", "Samples (Cluster method)"))
        self.samplesrandommethod_3.setText(_translate("MainWindow", "Maximum Neighbours"))
        self.rundcilabel_2.setText(_translate("MainWindow", "Run Optimisation"))
        self.comboBox.setItemText(0, _translate("MainWindow", "tsne"))
        self.samplesrandommethod_4.setText(_translate("MainWindow", "Maximum Exaggeration"))
        self.drmethodlabel.setText(_translate("MainWindow", "DR Algorithm"))
        self.samplesrandommethod_6.setText(_translate("MainWindow", "Iterations"))
        self.samplesrandommethod.setText(_translate("MainWindow", "Samples (Random Method)"))
        self.rundcilabel.setText(_translate("MainWindow", "Run DCI"))
        self.initlabel.setText(_translate("MainWindow", "Initialization"))
        self.loadmebeddingcsvedit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Load Embedding npy/csv</p></body></html>"))
        self.initselectionbox.setItemText(0, _translate("MainWindow", "default"))
        self.initselectionbox.setItemText(1, _translate("MainWindow", "random"))
        self.initselectionbox.setItemText(2, _translate("MainWindow", "pca"))
        self.statuslabel.setText(_translate("MainWindow", "Status: Awaiting input"))
        self.DataAnalysisLabel.setText(_translate("MainWindow", "Dimensionality Reduction"))
        self.dr_tsne.setText(_translate("MainWindow", "t-SNE"))
        self.label_9.setText(_translate("MainWindow", "Create Embedding"))
        self.label_5.setText(_translate("MainWindow", "Exaggeration"))
        self.label_8.setText(_translate("MainWindow", "Components"))
        self.label_7.setText(_translate("MainWindow", "Initialization"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "random"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "pca"))
        self.label_4.setText(_translate("MainWindow", "Perplexity"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "cosine"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "euclidean"))
        self.label_6.setText(_translate("MainWindow", "Distance"))
        self.label_11.setText(_translate("MainWindow", "Help"))
        self.whatdata_helpbtn.setText(_translate("MainWindow", "What data should I load?"))
        self.matbroken_helpbtn.setText(_translate("MainWindow", "My .mat isnt working"))
        self.csvbroken_helpbtn.setText(_translate("MainWindow", "My .csv files arent working"))
        self.HowDCI_helpbtn.setText(_translate("MainWindow", "How do I run DCI?"))
        self.HowBayes_helpbtn.setText(_translate("MainWindow", "How do I run Bayesion opt?"))
        self.Whatparams_helpbtn.setText(_translate("MainWindow", "What parameters should I use?"))
        self.Whatoutputs_helpbtn.setText(_translate("MainWindow", "What are the outputs?"))
        self.loadingbeecheck.setText(_translate("MainWindow", "Bee loading screen!"))
import resources_white_rc
